import localFont from "next/font/local";
import "./globals.css";
import Headernav from "./_components/Headernav";
import Footer from "./_components/Footer";
import ProviderApp from "./store/ProviderApp";
import MiniCart from "./_components/MiniCart";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "eCommerceX2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased relative `}>
        <ClerkProvider>
          <ProviderApp>
            <Headernav />
            {children}
            <Footer />
          </ProviderApp>
        </ClerkProvider>
      </body>
    </html>
  );
}
